# Generated by Django 3.2 on 2022-01-12 06:47

from django.db import migrations, models
import guarantee.models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantee',
            name='category',
            field=models.CharField(choices=[('mobile', '모바일/웨어러블'), ('home', '가전제품'), ('pc', 'PC/노트북'), ('office', '사무용품')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guarantee',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=guarantee.models.get_image_upload_path),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to=guarantee.models.get_image_upload_path),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='warranty_image',
            field=models.ImageField(default=1, upload_to=guarantee.models.get_image_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='paid_money',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='serial_number',
            field=models.CharField(blank=True, default='-', max_length=40),
        ),
        migrations.AlterModelTable(
            name='guarantee',
            table='guarantees',
        ),
    ]
