# Generated by Django 3.2 on 2022-01-08 08:18

from django.db import migrations, models
import guarantee.models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantee',
            name='product_image',
            field=models.ImageField(default=1, upload_to=guarantee.models.get_image_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guarantee',
            name='receipt_image',
            field=models.ImageField(default=1, upload_to=guarantee.models.get_image_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guarantee',
            name='warranty_image',
            field=models.ImageField(default=1, upload_to=guarantee.models.get_image_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='serial_number',
            field=models.CharField(blank=True, default='-', max_length=40),
        ),
    ]
