# Generated by Django 3.2 on 2022-01-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantee',
            name='serial_number',
            field=models.CharField(blank=True, default='-', max_length=40),
        ),
    ]
