# Generated by Django 3.2 on 2022-01-08 09:50

from django.db import migrations, models
import guarantee.models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantee', '0002_auto_20220108_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantee',
            name='paid_money',
            field=models.IntegerField(blank=True, null=True, validators=[guarantee.models.is_positive_number]),
        ),
    ]
