# Generated by Django 3.2 on 2022-01-10 10:34

from django.db import migrations, models
import guarantee.models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantee', '0003_alter_guarantee_paid_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantee',
            name='product_image',
            field=models.ImageField(null=True, upload_to=guarantee.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='receipt_image',
            field=models.ImageField(null=True, upload_to=guarantee.models.get_image_upload_path),
        ),
    ]
