# Generated by Django 3.2 on 2022-01-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantee', '0004_auto_20220110_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantee',
            name='paid_money',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
